name: Presubmit

on:
  pull_request:
    branches:
      - main

jobs:
  call-reusable-test:
    name: "Presubmit Validation Checks"
    uses: ./.github/workflows/reusable-test.yml
    with:
      runs_on: ubuntu-latest
